#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /login_check
    methods: ['POST']

api_refresh_token:
    path:       /token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
